version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - "server"
    ports:
      - 4200:4200
      - 80:80
    image: test/docker-spring-angular:frontend
    restart: unless-stopped

  server:
    container_name: server
    build: ./server
    ports:
      - 8080:8080
    image: test/docker-spring-angular:server
    restart: unless-stopped
